- name: Configure web servers via SSM
  hosts: "project_Slash:&env_Dev:&role_web"
  gather_facts: yes
  vars:
    nginx_pkg: nginx

  tasks:
    - name: Ensure nginx is present
      package:
        name: "{{ nginx_pkg }}"
        state: present

    - name: Drop homepage
      copy:
        dest: /usr/share/nginx/html/index.html
        content: |
          Hello from {{ inventory_hostname }} ({{ hostvars[inventory_hostname].get('env', 'unknown') }})

    - name: Enable & start nginx
      service:
        name: nginx
        state: started
        enabled: yes
